# Runtime settings
environment: 'production'
log-level: 'warning'

# Website
url-prefix: ''
app-title: "Ontology Spreadsheet Editor"

# Database and storage
database-uri: 'sqlite:////tmp/github-flask-ontospreaded.db'
index-path: 'ose_index'

# Repositories
repositories:
  # Where to look for repository configration. Possible values: 'repository' or 'local'
  source: 'repository'
  data:
    allow-load: no
    allow-save: no
    startup-repositories-path: 'startup-repositories.yaml'
    path: .onto-ed/config.yaml

# GitHub users with access
users:
  CaitlinNotley:
    initials: CN
    repositories:
      - AddictO
  CaitlinNotley702:
    initials: CN
    repositories:
      - AddictO
  alisonjwright:
    admin: true
    initials: AW
    repositories:
      - BCIO
      - AddictO
  b-gehrke:
    admin: true
    initials: BG
    repositories:
      - AddictO
      - BCIO
      - GMHO
  candicemooreucl:
    initials: CM
    repositories:
      - BCIO
  emilyjhayes:
    initials: EJH
    repositories:
      - BCIO
  jannahastings:
    admin: true
    initials: JH
    repositories:
      - AddictO
      - BCIO
      - GMHO
  ksoar:
    initials: KS
    repositories:
      - AddictO
  lzhang01:
    admin: true
    initials: LZ
    repositories:
      - AddictO
      - BCIO
      - GMHO
  oscarcastroserrano:
    initials: OC
    repositories:
      - BCIO
  paulinaschenk:
    admin: true
    initials: PS
    repositories:
      - BCIO
      - GMHO
  robertjwest:
    admin: true
    initials: RW
    repositories:
      - AddictO
      - BCIO
      - GMHO
  sharoncox:
    initials: SC
    repositories:
      - AddictO
  tomjuggler:
    initials: ZZ
    repositories:
      - AddictO
      - BCIO
  zcbtelh:
    initials: EH
    repositories:
      - BCIO
