#!/usr/bin/env node
/**
 * Generates shim files for Vue and @ontospreaded/js-core that re-export from window globals.
 * This allows dynamically loaded plugin modules to use the same Vue instance as the host app.
 * 
 * Run with: node scripts/generate-shims.mjs
 */

import { writeFileSync, mkdirSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputDir = resolve(__dirname, '../packages/ose-app/src/ose_app/static/js');

// Dynamically import Vue to get all its exports
async function generateVueShim() {
  const vue = await import('vue');
  const exports = Object.keys(vue).filter(k => k !== 'default');
  
  const lines = [
    '// AUTO-GENERATED FILE - Do not edit manually!',
    '// Generated by scripts/generate-shims.mjs',
    '// This shim re-exports Vue from window.Vue for dynamically loaded plugin modules.',
    '',
    'const V = window.Vue;',
    '',
    ...exports.map(name => `export const ${name} = V.${name};`),
    '',
    'export default V;',
    ''
  ];
  
  const content = lines.join('\n');
  const outputPath = resolve(outputDir, 'vue-shim.js');
  
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content);
  
  console.log(`Generated ${outputPath} with ${exports.length} exports`);
}

// Dynamically import @ontospreaded/js-core to get all its exports
async function generateOseJsCoreShim() {
  // Import from the built dist folder
  const oseJsCore = await import('../packages/ose-js-core/dist/index.js');
  const exports = Object.keys(oseJsCore).filter(k => k !== 'default');
  
  const lines = [
    '// AUTO-GENERATED FILE - Do not edit manually!',
    '// Generated by scripts/generate-shims.mjs', 
    '// This shim re-exports @ontospreaded/js-core from window.OseJsCore for dynamically loaded plugin modules.',
    '',
    'const C = window.OseJsCore;',
    '',
    ...exports.map(name => `export const ${name} = C.${name};`),
    '',
    'export default C;',
    ''
  ];
  
  const content = lines.join('\n');
  const outputPath = resolve(outputDir, 'ose-js-core-shim.js');
  
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content);
  
  console.log(`Generated ${outputPath} with ${exports.length} exports`);
}

async function main() {
  console.log('Generating shim files...\n');
  
  await generateVueShim();
  await generateOseJsCoreShim();
  
  console.log('\nDone!');
}

main().catch(err => {
  console.error('Error generating shims:', err);
  process.exit(1);
});
